### ISSUE TITLE
Star Citizen shows incorrect bindings for some buttons on VKB Gladiator NXT HOSAS

### ISSUE THREAD

**Issue by JDLuke** [Rexeh/joystick-diagrams#53] opened 2021-04-10 13:57 UTC
I wanted to be extremely detailed about this, so I'm marking up a pair of images showing the output of the program, with correct and incorrect values and notes added.
![Rexeh Feedback NXT Left 2021-04-10](https://user-images.githubusercontent.com/6942286/114272127-cb747e00-99e2-11eb-8fd4-b83bb3c63813.png)
![Rexeh Feedback NXT Right 2021-04-10](https://user-images.githubusercontent.com/6942286/114272129-ce6f6e80-99e2-11eb-9640-6583d6ea2501.png)

All that is from the version of the control layout currently present in my repo.  I'll tag it as '3.12.1' since 3.13 is coming out soon anyway and I believe there will be changes.  You probably want to get started on that new release immediately but I'm not playing in the PTU and don't have a configuration file to offer yet.

**Comment by Rexeh** [comment] 2021-04-10 17:04
Thanks for this, nice and clear.

The root cause of this is the multiple binds, I'd class this as modifiers and not something I currently deal with but is on the list todo.

NXT - Left as an example, for button 3 has 5 potential binds

v_toggle_qdrive_spooling
v_toggle_qdrive_engagement
v_toggle_mining_laser_type
v_toggle_mining_laser_type
v_starmap

The axis missing are down to missing elements in the template which I must have missed! From the looks of the file, this will suffer the same fate

NXT - Right for example has the following for the X axis (content dependent)

v_strafe_lateral
eva_strafe_lateral
gp_movex

The feature for modifiers is here - https://github.com/Rexeh/joystick-diagrams/issues/32

**Comment by JDLuke** [comment] 2021-04-14 18:57
Yeah, the multiple bindings get confusing even as a player!  Sometimes one is not sure which items are modal and which aren't and the current configuration UI really does not help with that.  The best you get is a message asking if it's OK for a binding to be added when that control is already bound to xxxxx.  Sometimes this is safe to accept, sometimes not.

For SC, a list of all current bindings for each control would be plenty (for me at least).  I really don't know how to address the more mode-driven stuff unless or until updates come out, and that's almost certain to come with a refactoring of the UI for bindings and a likely restructuring of the XML.

**Comment by Rexeh** [comment] 2021-04-14 19:00
> Yeah, the multiple bindings get confusing even as a player! Sometimes one is not sure which items are modal and which aren't and the current configuration UI really does not help with that. The best you get is a message asking if it's OK for a binding to be added when that control is already bound to xxxxx. Sometimes this is safe to accept, sometimes not.
> 
> For SC, a list of all current bindings for each control would be plenty (for me at least). I really don't know how to address the more mode-driven stuff unless or until updates come out, and that's almost certain to come with a refactoring of the UI for bindings and a likely restructuring of the XML.

Thanks Luke, I'll close this issue for now as it's linked to the other. I think however I have got a way forward in terms of how I'll extend the parser formats - It really will just be a case of spending time on it. The ideal solution is fully automating the SVG including all the drawing - but need to think about that further as to where I want the tool to go.

**Closed by Rexeh** 2021-04-14 19:00 UTC
